name: Go Build and Test
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go 1.21.5
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    # - name: Build Test
    #   run: go build -v ./...
    - name: Run container with PS to get process system
      run: sudo go run main.go run /bin/ps
