name: Go container compare SO vs container ps
on:
  push:
    branches:
      - master

jobs:
  compare-container-vs-so-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run ls /bin/ps
      run: ls /bin
    - name: Run ps in our OS without container
      run: ps 

    - name: Set up Go 1.21.5
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5
    - name: Run PS inside of the container
      run: sudo go run main.go run /bin/ps -a
